site_name: Snitcher
site_description: 'Snitcher captures global crashes, enabling easy redirection to the exception tracing screen for swift recovery.'
site_author: 'Jaewoong (skydoves)'
site_url: 'https://github.com/skydoves/snitcher'
edit_uri: 'tree/main/docs/'
remote_branch: gh-pages

docs_dir: docs

# Navigation
nav:
  - 'Overview': index.md
  - 'Trace Global Exception': trace-global-exception.md
  - 'Exception Screen': custom-trace-screen.md
  - 'Launcher Activity': custom-launcher-activity.md
  - 'Snitcher Theme': custom-theme.md
  - 'Build Types': custom-build-type.md
  - 'Trace Strategy': trace-strategy.md
  - 'Sponsor ðŸ©·': sponsor.md
    
# Repository
repo_name: 'snitcher'
repo_url: 'https://github.com/skydoves/snitcher'

# Configuration
theme:
  name: 'material'
  language: 'en'
  icon:
    logo: material/owl

  palette:
    primary: 'blue'
    accent: 'blue'
    scheme: slate

  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

  features:
    - content.tabs.link  
    - content.code.copy
    - content.code.annotate

extra:
  analytics:
    provider: google
    property: G-1SBY14Q79E    

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details